baseURL: 'https://simondev.win/'
languageCode: en-us
title: Simon The Rising Front-End Star
theme: PaperMod
canonifyURLs: false

params:
  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  homeInfoParams:
        Title: Hello! I'm glad you're here :D
        Content: Welcome to my blog, where you can see how my programming journey goes! 

  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/profile.php?id=100011552317797"
    - name: github
      url: "https://github.com/Szymonbaczek/quickstart"

     
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
